# Generated by Django 4.1.6 on 2023-02-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person1',
            name='image',
        ),
    ]
