# Generated by Django 4.1.6 on 2023-02-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_image_person1_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person1',
            old_name='images',
            new_name='image',
        ),
    ]
