# Generated by Django 4.1.6 on 2023-02-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_images_person1_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person1',
            name='image',
            field=models.BinaryField(),
        ),
    ]
